version: '3'

services:
  app:
    build:
      context:
    ports:
      - "8000:8000"
    volumes:
      - ./ProjectSupport:/ProjectSupport
    command: python manage.py runserver
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - ./ProjectSupport/.env
    ports:
      - "5432:5432"
