# Generated by Django 3.2.8 on 2021-10-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state_of_request',
            field=models.TextField(choices=[('Не решён', 'не решён'), ('Решён', 'решён'), ('Заморожен', 'заморожен')], default=('Не решён', 'не решён'), max_length=20),
        ),
    ]
