# Generated by Django 3.2.8 on 2021-10-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_ticket_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state_of_request',
            field=models.CharField(choices=[('Не решён', 'не решён'), ('Решён', 'решён'), ('Заморожен', 'заморожен')], default=('Не решён', 'не решён'), max_length=50),
        ),
    ]
